name: jaludash

services:
  jaludash:
    image: jaludash:latest
    build: .
    container_name: jaludash
    restart: unless-stopped
    ports:
      - "4173:4173"
    networks:
      - proxy
    volumes:
      - jaludash-data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaludash.rule=Host(`jaludash.local.jalubru.com`)"
      - "traefik.http.routers.jaludash.entrypoints=https"
      - "traefik.http.routers.jaludash.tls=true"
      - "traefik.http.services.jaludash.loadbalancer.server.port=4173"

volumes:
  jaludash-data:

networks:
  proxy:
    external: true
